apiVersion: v1
kind: Service
metadata:
  name: customer-frontend-service
spec:
  selector:
    app: customer-frontend
  ports:
    - protocol: TCP
      port: 3002      # Port, auf dem das Frontend verfügbar ist
      targetPort: 3002 # Der Port im Container
