apiVersion: v1
kind: Service
metadata:
  name: order-frontend-service
spec:
  selector:
    app: order-frontend  # Selektiert Pods mit dem Label "app: order-frontend"
  ports:
    - protocol: TCP
      port: 3001          # Der Port, über den der Service erreichbar ist
      targetPort: 3001    # Der Port im Container
  type: ClusterIP         # Standard-Service-Typ (optional)
