server:
  port: 8082
  ssl:
    enabled: true
    key-store: classpath:keystore.p12
    key-store-password: password
    key-store-type: PKCS12
    key-alias: tomcat
  servlet:
    context-path: /api
spring:
  application:
    name: kata-02