### GET request to customer-backend
GET https://localhost:8082/api/v1/customers

### GET request to customer-backend
GET https://localhost:8082/api/v1/customers/10

### PUT request to customer-backend
PUT https://localhost:8082/api/v1/customers/2
Content-Type: application/json

{
  "name": "John Doe 42"
}

### POST Insert a new customer
POST https://localhost:8082/api/v1/customers
Content-Type: application/json

{
  "name": "Anita Lopez"
}

### DELETE request to customer-backend
DELETE https://localhost:8082/api/v1/customers/3


